### ISSUE TITLE
Conflicting project name

### ISSUE THREAD

**Issue by KanoczTomas** [frankbraun/codechain#3]
Hey, I really like the project, but when I tried googling it I found the name is taken by this: https://github.com/CodeChain-io/codechain

As this is an early stage of the project, rebranding it might be less painful.

Anyway, just wanted you to be aware of the name conflict ... it might not make a difference, thought I would still let you know ....

**Comment by frankbraun** [comment]
Hi @KanoczTomas, I'm glad you like the project and thanks for the feedback.

That project seems to have a totally different scope so we decided to keep the name.
